FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN apk add --no-cache git && CGO_ENABLED=0 GOOS=linux go build -o hello-world main.go


# ------------



FROM alpine:latest

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

WORKDIR /home/appuser

COPY --from=builder /app/hello-world .

EXPOSE 8080

CMD ["./hello-world”]